// TEMPORARY DATA

export let role = "admin";

export const teachersData = [
  {
    id: 1,
    teacherId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["1B", "2A", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    teacherId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics", "Chemistry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    teacherId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    teacherId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    teacherId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Music", "History"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    teacherId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Physics"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    teacherId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["English", "Spanish"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    teacherId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Math", "Geometry"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    teacherId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Literature", "English"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    teacherId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    subjects: ["Biology"],
    classes: ["5A", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const studentsData = [
  {
    id: 1,
    studentId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    studentId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    studentId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    studentId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    studentId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    studentId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    studentId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    studentId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    studentId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    studentId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    grade: 5,
    class: "5A",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    students: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    students: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    students: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    students: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    students: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    students: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    students: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    students: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    students: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    students: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const subjectsData = [
  {
    id: 1,
    name: "Math",
    masse : 200,
    teachers: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "English",
    masse : 200,
    teachers: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Physics",
    masse : 200,
    teachers: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Chemistry",
    masse : 200,
    teachers: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Biology",
    masse : 200,
    teachers: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "History",
    masse : 200,
    teachers: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Geography",
    masse : 200,
    teachers: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Art",
    masse : 200,
    teachers: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Music",
    masse : 200,
    teachers: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Literature",
    masse : 200,
    teachers: ["Effie Lynch", "Brett Flowers"],
  },
];

export const classesData = [
  {
    id: 1,
    name: "1A",
    capacity: 20,
    grade: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "2B",
    capacity: 22,
    grade: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "3C",
    capacity: 20,
    grade: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "4B",
    capacity: 18,
    grade: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "5A",
    capacity: 16,
    grade: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "5B",
    capacity: 20,
    grade: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "7A",
    capacity: 18,
    grade: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "6B",
    capacity: 22,
    grade: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "6C",
    capacity: 18,
    grade: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "6D",
    capacity: 20,
    grade: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const lessonsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Tommy Wise",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Rhoda Frank",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Della Dunn",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Bruce Rodriguez",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Birdie Butler",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Bettie Oliver",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Herman Howard",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Lucinda Thomas",
  },
  {
    id: 9,
    subject: "Physics",
    class: "6C",
    teacher: "Ronald Roberts",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "4B",
    teacher: "Julia Pittman",
  },
];

export const examsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const resultsData = [
  {
    id: 1,
    subject: "Math",
    class: "1A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 2,
    subject: "English",
    class: "2A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 3,
    subject: "Science",
    class: "3A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 4,
    subject: "Social Studies",
    class: "1B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 5,
    subject: "Art",
    class: "4A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 6,
    subject: "Music",
    class: "5A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 7,
    subject: "History",
    class: "6A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 8,
    subject: "Geography",
    class: "6B",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 9,
    subject: "Physics",
    class: "7A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
  {
    id: 10,
    subject: "Chemistry",
    class: "8A",
    teacher: "John Doe",
    student: "John Doe",
    date: "2025-01-01",
    type: "exam",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    date: "2025-04-20",
    time: "10:00 AM - 12:00 PM",
    description: "Enjoy a fun trip to the lake with classmates.",
  },
  {
    id: 2,
    title: "Art Workshop",
    date: "2025-04-20",
    time: "1:00 PM - 3:00 PM",
    description: "Learn painting techniques in this interactive workshop.",
  },
  {
    id: 3,
    title: "Music Concert",
    date: "2025-04-20",
    time: "4:00 PM - 6:00 PM",
    description: "Experience live music performances by students.",
  },
  {
    id: 4,
    title: "School Play",
    date: "2025-04-21",
    time: "10:00 AM - 12:00 PM",
    description: "Watch an entertaining play performed by students.",
  },
  {
    id: 5,
    title: "Science Workshop",
    date: "2025-04-21",
    time: "1:00 PM - 3:00 PM",
    description: "Explore exciting science experiments and activities.",
  },
  {
    id: 6,
    title: "Book Fair",
    date: "2025-04-21",
    time: "4:00 PM - 6:00 PM",
    description: "Browse and purchase books at the school book fair.",
  },
  {
    id: 7,
    title: "Science Fair",
    date: "2025-04-22",
    time: "10:00 AM - 12:00 PM",
    description: "Showcase innovative science projects by students.",
  },
  {
    id: 8,
    title: "Math Quiz",
    date: "2025-04-22",
    time: "1:00 PM - 3:00 PM",
    description: "Participate in a challenging math quiz competition.",
  },
  {
    id: 9,
    title: "Drama Rehearsal",
    date: "2025-04-22",
    time: "4:00 PM - 6:00 PM",
    description: "Prepare for the upcoming drama performance.",
  },
  {
    id: 10,
    title: "Math Olympiad",
    date: "2025-04-23",
    time: "10:00 AM - 12:00 PM",
    description: "Compete in the annual math olympiad.",
  },
  {
    id: 11,
    title: "Art Exhibition",
    date: "2025-04-23",
    time: "1:00 PM - 3:00 PM",
    description: "Admire artwork created by talented students.",
  },
  {
    id: 12,
    title: "Sports Practice",
    date: "2025-04-23",
    time: "4:00 PM - 6:00 PM",
    description: "Practice for the upcoming sports day events.",
  },
  {
    id: 13,
    title: "Art Exhibition",
    date: "2025-04-24",
    time: "10:00 AM - 12:00 PM",
    description: "Explore creative art pieces by students.",
  },
  {
    id: 14,
    title: "Music Workshop",
    date: "2025-04-24",
    time: "1:00 PM - 3:00 PM",
    description: "Learn to play musical instruments in this workshop.",
  },
  {
    id: 15,
    title: "Sports Day Preparation",
    date: "2025-04-24",
    time: "4:00 PM - 6:00 PM",
    description: "Get ready for the sports day activities.",
  },
  {
    id: 16,
    title: "Sports Day",
    date: "2025-04-25",
    time: "10:00 AM - 12:00 PM",
    description: "Participate in exciting sports events and games.",
  },
  {
    id: 17,
    title: "Cultural Dance",
    date: "2025-04-25",
    time: "1:00 PM - 3:00 PM",
    description: "Enjoy cultural dance performances by students.",
  },
  {
    id: 18,
    title: "Award Ceremony",
    date: "2025-04-25",
    time: "4:00 PM - 6:00 PM",
    description: "Celebrate achievements with an award ceremony.",
  },
  {
    id: 19,
    title: "Parent-Teacher Meeting",
    date: "2025-04-26",
    time: "10:00 AM - 12:00 PM",
    description: "Discuss student progress with teachers.",
  },
  {
    id: 20,
    title: "Career Guidance",
    date: "2025-04-26",
    time: "1:00 PM - 3:00 PM",
    description: "Attend a session on career guidance and planning.",
  },
  {
    id: 21,
    title: "Farewell Party",
    date: "2025-04-26",
    time: "4:00 PM - 6:00 PM",
    description: "Bid farewell to graduating students.",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About 4A Math Test",
    description: "Enjoy a fun trip to the lake with classmates.",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About 4A English Test",
    description: "Learn painting techniques in this interactive workshop.",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 4A Science Test",
    description: "Experience live music performances by students.",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About 4A Social Studies Test",
    description: "Watch an entertaining play performed by students.",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 4A Art Test",
    description: "Explore exciting science experiments and activities.",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About 4A Music Test",
    description: "Browse and purchase books at the school book fair.",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4A History Test",
    description: "Showcase innovative science projects by students.",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4A Geography Test",
    description: "Participate in a challenging math quiz competition.",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 4A Physics Test",
    description: "Prepare for the upcoming drama performance.",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 4A Chemistry Test",
    description: "Compete in the annual math olympiad.",
    date: "2025-01-01",
  },
];


export const calendarEvents = [
  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 3, 7, 8, 0),
    end: new Date(2025, 3, 7, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 7, 9, 0),
    end: new Date(2025, 3, 7, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 7, 10, 0),
    end: new Date(2025, 3, 7, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 7, 11, 0),
    end: new Date(2025, 3, 7, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 3, 7, 13, 0),
    end: new Date(2025, 3, 7, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 3, 7, 14, 0),
    end: new Date(2025, 3, 7, 14, 45),
  },

  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 3, 8, 8, 0),
    end: new Date(2025, 3, 8, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 8, 9, 0),
    end: new Date(2025, 3, 8, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 8, 10, 0),
    end: new Date(2025, 3, 8, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 8, 11, 0),
    end: new Date(2025, 3, 8, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 3, 8, 13, 0),
    end: new Date(2025, 3, 8, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 3, 8, 14, 0),
    end: new Date(2025, 3, 8, 14, 45),
  },

  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 3, 9, 8, 0),
    end: new Date(2025, 3, 9, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 9, 9, 0),
    end: new Date(2025, 3, 9, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 9, 10, 0),
    end: new Date(2025, 3, 9, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 9, 11, 0),
    end: new Date(2025, 3, 9, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 3, 9, 13, 0),
    end: new Date(2025, 3, 9, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 3, 9, 14, 0),
    end: new Date(2025, 3, 9, 14, 45),
  },

  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 3, 10, 8, 0),
    end: new Date(2025, 3, 10, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 10, 9, 0),
    end: new Date(2025, 3, 10, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 10, 10, 0),
    end: new Date(2025, 3, 10, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 10, 11, 0),
    end: new Date(2025, 3, 10, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 3, 10, 13, 0),
    end: new Date(2025, 3, 10, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 3, 10, 14, 0),
    end: new Date(2025, 3, 10, 14, 45),
  },

  {
    title: "Math",
    allDay: false,
    start: new Date(2025, 3, 11, 8, 0),
    end: new Date(2025, 3, 11, 8, 45),
  },
  {
    title: "English",
    allDay: false,
    start: new Date(2025, 3, 11, 9, 0),
    end: new Date(2025, 3, 11, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2025, 3, 11, 10, 0),
    end: new Date(2025, 3, 11, 10, 45),
  },
  {
    title: "Physics",
    allDay: false,
    start: new Date(2025, 3, 11, 11, 0),
    end: new Date(2025, 3, 11, 11, 45),
  },
  {
    title: "Chemistry",
    allDay: false,
    start: new Date(2025, 3, 11, 13, 0),
    end: new Date(2025, 3, 11, 13, 45),
  },
  {
    title: "History",
    allDay: false,
    start: new Date(2025, 3, 11, 14, 0),
    end: new Date(2025, 3, 11, 14, 45),
  },
];
